In [1]:
import pandas as pd

In [2]:
genres = pd.read_csv('genre.csv')

In [3]:
genres

    genre_id                name
0          1                Rock
1          2                Jazz
2          3               Metal
3          4  Alternative & Punk
4          5       Rock And Roll
5          6               Blues
6          7               Latin
7          8              Reggae
8          9                 Pop
9         10          Soundtrack
10        11          Bossa Nova
11        12      Easy Listening
12        13         Heavy Metal
13        14            R&B/Soul
14        15   Electronica/Dance
15        16               World
16        17         Hip Hop/Rap
17        18     Science Fiction
18        19            TV Shows
19        20    Sci Fi & Fantasy
20        21               Drama
21        22              Comedy
22        23         Alternative
23        24           Classical
24        25               Opera

In [4]:
genres.columns

Index(['genre_id', 'name'], dtype='object')

In [5]:
genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genre_id  25 non-null     int64
 1   name      25 non-null     object
dtypes: int64(1), object(1)
memory usage: 528.0+ bytes

In [6]:
artist = pd.read_csv('artist.csv')

In [7]:
artist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 275 entries, 0 to 274
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   artist_id  275 non-null    int64
 1   name       275 non-null    object
dtypes: int64(1), object(1)
memory usage: 4.4+ KB

In [8]:
artist.columns

Index(['artist_id', 'name'], dtype='object')

In [9]:
media_type = pd.read_csv('media_type.csv')

In [10]:
media_type.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   media_type_id  5 non-null      int64
 1   name           5 non-null      object
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes

In [11]:
media_type.columns

Index(['media_type_id', 'name'], dtype='object')

In [12]:
playlist = pd.read_csv('playlist.csv')

In [13]:
playlist

    playlist_id                        name
0             1                       Music
1             2                      Movies
2             3                    TV Shows
3             4                  Audiobooks
4             5                  90’s Music
5             6                  Audiobooks
6             7                      Movies
7             8                       Music
8             9                Music Videos
9            10                    TV Shows
10           11             Brazilian Music
11           12                   Classical
12           13   Classical 101 - Deep Cuts
13           14  Classical 101 - Next Steps
14           15  Classical 101 - The Basics
15           16                      Grunge
16           17         Heavy Metal Classic
17           18                 On-The-Go 1

In [14]:
playlist.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18 entries, 0 to 17
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   playlist_id  18 non-null     int64
 1   name         18 non-null     object
dtypes: int64(1), object(1)
memory usage: 416.0+ bytes

In [15]:
playlist.columns

Index(['playlist_id', 'name'], dtype='object')

In [16]:
employee = pd.read_csv('employee.csv')

In [17]:
employee.head()

,employee_id,last_name,first_name,title,reports_to,levels,birthdate,hire_date,address,city,state,country,postal_code,phone,fax,email
0,1,Adams,Andrew,General Manager,9.0,L6,18-02-1962 00:00,14-08-2016 00:00,11120 Jasper Ave NW,Edmonton,AB,Canada,T5K 2N1,+1 (780) 428-9482,+1 (780) 428-3457,andrew@chinookcorp.com
1,2,Edwards,Nancy,Sales Manager,1.0,L4,08-12-1958 00:00,01-05-2016 00:00,825 8 Ave SW,Calgary,AB,Canada,T2P 2T3,+1 (403) 262-3443,+1 (403) 262-3322,nancy@chinookcorp.com
2,3,Peacock,Jane,Sales Support Agent,2.0,L1,29-08-1973 00:00,01-04-2017 00:00,1111 6 Ave SW,Calgary,AB,Canada,T2P 5M5,+1 (403) 262-3443,+1 (403) 262-6712,jane@chinookcorp.com
3,4,Park,Margaret,Sales Support Agent,2.0,L1,19-09-1947 00:00,03-05-2017 00:00,683 10 Street SW,Calgary,AB,Canada,T2P 5G3,+1 (403) 263-4423,+1 (403) 263-4289,margaret@chinookcorp.com
4,5,Johnson,Steve,Sales Support Agent,2.0,L1,03-03-1965 00:00,17-10-2017 00:00,7727B 41 Ave,Calgary,AB,Canada,T3B 1Y7,1 (780) 836-9987,1 (780) 836-9543,steve@chinookcorp.com

In [18]:
employee.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   employee_id  9 non-null      int64
 1   last_name    9 non-null      object
 2   first_name   9 non-null      object
 3   title        9 non-null      object
 4   reports_to   8 non-null      float64
 5   levels       9 non-null      object
 6   birthdate    9 non-null      object
 7   hire_date    9 non-null      object
 8   address      9 non-null      object
 9   city         9 non-null      object
 10  state        9 non-null      object
 11  country      9 non-null      object
 12  postal_code  9 non-null      object
 13  phone        9 non-null      object
 14  fax          9 non-null      object
 15  email        9 non-null      object
dtypes: float64(1), int64(1), object(14)
memory usage: 1.2+ KB

In [19]:
employee.columns

Index(['employee_id', 'last_name', 'first_name', 'title', 'reports_to',
       'levels', 'birthdate', 'hire_date', 'address', 'city', 'state',
       'country', 'postal_code', 'phone', 'fax', 'email'],
      dtype='object')

In [20]:
album = pd.read_csv('album.csv')
album

     album_id                                              title  artist_id
0         156                                And Justice For All         50
1         208                               Black Light Syndrome        136
2         257  20th Century Masters - The Millennium Collecti...        179
3         296                      A Copland Celebration, Vol. I        230
4          94                         A Matter of Life and Death         90
..        ...                                                ...        ...
342       239                                                War        150
343         8                                     Warner 25 Anos          6
344       334                       Weill: The Seven Deadly Sins        264
345       267                                             Worlds        202
346       240                                            Zooropa        150

[347 rows x 3 columns]

In [21]:
album.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 347 entries, 0 to 346
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   album_id   347 non-null    int64
 1   title      347 non-null    object
 2   artist_id  347 non-null    int64
dtypes: int64(2), object(1)
memory usage: 8.3+ KB

In [22]:
list(album.columns)

['album_id', 'title', 'artist_id']

In [23]:
customer = pd.read_csv('customer.csv')
customer

,customer_id,first_name,last_name,company,address,city,state,country,postal_code,phone,fax,email,support_rep_id
0,1,Luís,Gonçalves,Embraer - Empresa Brasileira de Aeronáutica S.A.,"Av. Brigadeiro Faria Lima, 2170",São José dos Campos,SP,Brazil,12227-000,+55 (12) 3923-5555,+55 (12) 3923-5566,luisg@embraer.com.br,3
1,2,Leonie,Köhler,NaN,Theodor-Heuss-Straße 34,Stuttgart,NaN,Germany,70174,+49 0711 2842222,NaN,leonekohler@surfeu.de,5
2,3,François,Tremblay,NaN,1498 rue Bélanger,Montréal,QC,Canada,H2G 1A7,+1 (514) 721-4711,NaN,ftremblay@gmail.com,3
3,4,Bjørn,Hansen,NaN,Ullevålsveien 14,Oslo,NaN,Norway,171,+47 22 44 22 22,NaN,bjorn.hansen@yahoo.no,4
4,5,František,Wichterlová,JetBrains s.r.o.,Klanova 9/506,Prague,NaN,Czech Republic,14700,+420 2 4172 5555,+420 2 4172 5555,frantisekw@jetbrains.com,4
5,6,Helena,Holý,NaN,Rilská 3174/6,Prague,NaN,Czech Republic,14300,+420 2 4177 0449,NaN,hholy@gmail.com,5
6,7,Astrid,Gruber,NaN,"Rotenturmstraße 4, 1010 Innere Stadt",Vienne,NaN,Austria,1010,+43 01 5134505,NaN,astrid.gruber@apple.at,5
7,8,Daan,Peeters,NaN,Grétrystraat 63,Brussels,NaN,Belgium,1000,+32 02 219 03 03,NaN,daan_peeters@apple.be,4
8,9,Kara,Nielsen,NaN,Sønder Boulevard 51,Copenhagen,NaN,Denmark,1720,+453 3331 9991,NaN,kara.nielsen@jubii.dk,4
9,10,Eduardo,Martins,Woodstock Discos,"Rua Dr. Falcão Filho, 155",São Paulo,SP,Brazil,01007-010,+55 (11) 3033-5446,+55 (11) 3033-4564,eduardo@woodstock.com.br,4
10,11,Alexandre,Rocha,Banco do Brasil S.A.,"Av. Paulista, 2022",São Paulo,SP,Brazil,01310-200,+55 (11) 3055-3278,+55 (11) 3055-8131,alero@uol.com.br,5
11,12,Roberto,Almeida,Riotur,"Praça Pio X, 119",Rio de Janeiro,RJ,Brazil,20040-020,+55 (21) 2271-7000,+55 (21) 2271-7070,roberto.almeida@riotur.gov.br,3
12,13,Fernanda,Ramos,NaN,Qe 7 Bloco G,Brasília,DF,Brazil,71020-677,+55 (61) 3363-5547,+55 (61) 3363-7855,fernadaramos4@uol.com.br,4
13,14,Mark,Philips,Telus,8210 111 ST NW,Edmonton,AB,Canada,T6G 2C7,+1 (780) 434-4554,+1 (780) 434-5565,mphilips12@shaw.ca,5
14,15,Jennifer,Peterson,Rogers Canada,700 W Pender Street,Vancouver,BC,Canada,V6C 1G8,+1 (604) 688-2255,+1 (604) 688-8756,jenniferp@rogers.ca,3
15,16,Frank,Harris,Google Inc.,1600 Amphitheatre Parkway,Mountain View,CA,USA,94043-1351,+1 (650) 253-0000,+1 (650) 253-0000,fharris@google.com,4
16,17,Jack,Smith,Microsoft Corporation,1 Microsoft Way,Redmond,WA,USA,98052-8300,+1 (425) 882-8080,+1 (425) 882-8081,jacksmith@microsoft.com,5
17,18,Michelle,Brooks,NaN,627 Broadway,New York,NY,USA,10012-2612,+1 (212) 221-3546,+1 (212) 221-4679,michelleb@aol.com,3
18,19,Tim,Goyer,Apple Inc.,1 Infinite Loop,Cupertino,CA,USA,95014,+1 (408) 996-1010,+1 (408) 996-1011,tgoyer@apple.com,3
19,20,Dan,Miller,NaN,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,+1 (650) 644-3358,NaN,dmiller@comcast.com,4
20,21,Kathy,Chase,NaN,801 W 4th Street,Reno,NV,USA,89503,+1 (775) 223-7665,NaN,kachase@hotmail.com,5
21,22,Heather,Leacock,NaN,120 S Orange Ave,Orlando,FL,USA,32801,+1 (407) 999-7788,NaN,hleacock@gmail.com,4
22,23,John,Gordon,NaN,69 Salem Street,Boston,MA,USA,2113,+1 (617) 522-1333,NaN,johngordon22@yahoo.com,4
23,24,Frank,Ralston,NaN,162 E Superior Street,Chicago,IL,USA,60611,+1 (312) 332-3232,NaN,fralston@gmail.com,3
24,25,Victor,Stevens,NaN,319 N. Frances Street,Madison,WI,USA,53703,+1 (608) 257-0597,NaN,vstevens@yahoo.com,5
25,26,Richard,Cunningham,NaN,2211 W Berry Street,Fort Worth,TX,USA,76110,+1 (817) 924-7272,NaN,ricunningham@hotmail.com,4
26,27,Patrick,Gray,NaN,1033 N Park Ave,Tucson,AZ,USA,85719,+1 (520) 622-4200,NaN,patrick.gray@aol.com,4
27,28,Julia,Barnett,NaN,302 S 700 E,Salt Lake City,UT,USA,84102,+1 (801) 531-7272,NaN,jubarnett@gmail.com,5
28,29,Robert,Brown,NaN,796 Dundas Street West,Toronto,ON,Canada,M6J 1V1,+1 (416) 363-8888,NaN,robbrown@shaw.ca,3
29,30,Edward,Francis,NaN,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,+1 (613) 234-3322,NaN,edfrancis@yachoo.ca,3
30,31,Martha,Silk,NaN,194A Chain Lake Drive,Halifax,NS,Canada,B3S 1C5,+1 (902) 450-0450,NaN,marthasilk@gmail.com,5
31,32,Aaron,Mitchell,NaN,696 Osborne Street,Winnipeg,MB,Canada,R3L 2B9,+1 (204) 452-6452,NaN,aaronmitchell@yahoo.ca,4
32,33,Ellie,Sullivan,NaN,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,+1 (867) 920-2233,NaN,ellie.sullivan@shaw.ca,3
33,34,João,Fernandes,NaN,Rua da Assunção 53,Lisbon,NaN,Portugal,NaN,+351 (213) 466-111,NaN,jfernandes@yahoo.pt,4
34,35,Madalena,Sampaio,NaN,"Rua dos Campeões Europeus de Viena, 4350",Porto,NaN,Portugal,NaN,+351 (225) 022-448,NaN,masampaio@sapo.pt,4
35,36,Hannah,Schneider,NaN,Tauentzienstraße 8,Berlin,NaN,Germany,10789,+49 030 26550280,NaN,hannah.schneider@yahoo.de,5
36,37,Fynn,Zimmermann,NaN,Berger Straße 10,Frankfurt,NaN,Germany,60316,+49 069 40598889,NaN,fzimmermann@yahoo.de,3
37,38,Niklas,Schröder,NaN,Barbarossastraße 19,Berlin,NaN,Germany,10779,+49 030 2141444,NaN,nschroder@surfeu.de,3
38,39,Camille,Bernard,NaN,"4, Rue Milton",Paris,NaN,France,75009,+33 01 49 70 65 65,NaN,camille.bernard@yahoo.fr,4
39,40,Dominique,Lefebvre,NaN,"8, Rue Hanovre",Paris,NaN,France,75002,+33 01 47 42 71 71,NaN,dominiquelefebvre@gmail.com,4
40,41,Marc,Dubois,NaN,"11, Place Bellecour",Lyon,NaN,France,69002,+33 04 78 30 30 30,NaN,marc.dubois@hotmail.com,5
41,42,Wyatt,Girard,NaN,"9, Place Louis Barthou",Bordeaux,NaN,France,33000,+33 05 56 96 96 96,NaN,wyatt.girard@yahoo.fr,3
42,43,Isabelle,Mercier,NaN,"68, Rue Jouvence",Dijon,NaN,France,21000,+33 03 80 73 66 99,NaN,isabelle_mercier@apple.fr,3
43,44,Terhi,Hämäläinen,NaN,Porthaninkatu 9,Helsinki,NaN,Finland,530,+358 09 870 2000,NaN,terhi.hamalainen@apple.fi,3
44,45,Ladislav,Kovács,NaN,Erzsébet krt. 58.,Budapest,NaN,Hungary,H-1073,NaN,NaN,ladislav_kovacs@apple.hu,3
45,46,Hugh,O'Reilly,NaN,3 Chatham Street,Dublin,Dublin,Ireland,NaN,+353 01 6792424,NaN,hughoreilly@apple.ie,3
46,47,Lucas,Mancini,NaN,"Via Degli Scipioni, 43",Rome,RM,Italy,192,+39 06 39733434,NaN,lucas.mancini@yahoo.it,5
47,48,Johannes,Van der Berg,NaN,Lijnbaansgracht 120bg,Amsterdam,VV,Netherlands,1016,+31 020 6223130,NaN,johavanderberg@yahoo.nl,5
48,49,Stanisław,Wójcik,NaN,Ordynacka 10,Warsaw,NaN,Poland,00-358,+48 22 828 37 39,NaN,stanisław.wójcik@wp.pl,4
49,50,Enrique,Muñoz,NaN,C/ San Bernardo 85,Madrid,NaN,Spain,28015,+34 914 454 454,NaN,enrique_munoz@yahoo.es,5
50,51,Joakim,Johansson,NaN,Celsiusg. 9,Stockholm,NaN,Sweden,11230,+46 08-651 52 52,NaN,joakim.johansson@yahoo.se,5
51,52,Emma,Jones,NaN,202 Hoxton Street,London,NaN,United Kingdom,N1 5LH,+44 020 7707 0707,NaN,emma_jones@hotmail.com,3
52,53,Phil,Hughes,NaN,113 Lupus St,London,NaN,United Kingdom,SW1V 3EN,+44 020 7976 5722,NaN,phil.hughes@gmail.com,3
53,54,Steve,Murray,NaN,110 Raeburn Pl,Edinburgh,NaN,United Kingdom,EH4 1HH,+44 0131 315 3300,NaN,steve.murray@yahoo.uk,5
54,55,Mark,Taylor,NaN,421 Bourke Street,Sidney,NSW,Australia,2010,+61 (02) 9332 3633,NaN,mark.taylor@yahoo.au,4
55,56,Diego,Gutiérrez,NaN,307 Macacha Güemes,Buenos Aires,NaN,Argentina,1106,+54 (0)11 4311 4333,NaN,diego.gutierrez@yahoo.ar,4
56,57,Luis,Rojas,NaN,"Calle Lira, 198",Santiago,NaN,Chile,NaN,+56 (0)2 635 4444,NaN,luisrojas@yahoo.cl,5
57,58,Manoj,Pareek,NaN,"12,Community Centre",Delhi,NaN,India,110017,+91 0124 39883988,NaN,manoj.pareek@rediff.com,3
58,59,Rishabh,Mishra,NaN,"3,Raj Bhavan Road",Bangalore,NaN,India,560001,+91 080 22289999,NaN,rishabh_mishra@yahoo.in,3

In [24]:
customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     59 non-null     int64
 1   first_name      59 non-null     object
 2   last_name       59 non-null     object
 3   company         10 non-null     object
 4   address         59 non-null     object
 5   city            59 non-null     object
 6   state           30 non-null     object
 7   country         59 non-null     object
 8   postal_code     55 non-null     object
 9   phone           58 non-null     object
 10  fax             12 non-null     object
 11  email           59 non-null     object
 12  support_rep_id  59 non-null     int64
dtypes: int64(2), object(11)
memory usage: 6.1+ KB

In [25]:
customer.columns

Index(['customer_id', 'first_name', 'last_name', 'company', 'address', 'city',
       'state', 'country', 'postal_code', 'phone', 'fax', 'email',
       'support_rep_id'],
      dtype='object')

In [26]:
invoice = pd.read_csv('invoice.csv')

In [27]:
invoice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   invoice_id           614 non-null    int64
 1   customer_id          614 non-null    int64
 2   invoice_date         614 non-null    object
 3   billing_address      614 non-null    object
 4   billing_city         614 non-null    object
 5   billing_state        310 non-null    object
 6   billing_country      614 non-null    object
 7   billing_postal_code  559 non-null    object
 8   total                614 non-null    float64
dtypes: float64(1), int64(2), object(6)
memory usage: 43.3+ KB

In [28]:
invoice.columns

Index(['invoice_id', 'customer_id', 'invoice_date', 'billing_address',
       'billing_city', 'billing_state', 'billing_country',
       'billing_postal_code', 'total'],
      dtype='object')

In [29]:
track = pd.read_csv('track.csv')

In [30]:
track.columns

Index(['track_id', 'name', 'album_id', 'media_type_id', 'genre_id', 'composer',
       'milliseconds', 'bytes', 'unit_price'],
      dtype='object')

In [31]:
track.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3503 entries, 0 to 3502
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   track_id       3503 non-null   int64
 1   name           3503 non-null   object
 2   album_id       3503 non-null   int64
 3   media_type_id  3503 non-null   int64
 4   genre_id       3503 non-null   int64
 5   composer       2525 non-null   object
 6   milliseconds   3503 non-null   int64
 7   bytes          3503 non-null   int64
 8   unit_price     3503 non-null   float64
dtypes: float64(1), int64(6), object(2)
memory usage: 246.4+ KB

In [45]:
invoice_line = pd.read_csv('invoice_line.csv')
invoice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   invoice_id           614 non-null    int64
 1   customer_id          614 non-null    int64
 2   invoice_date         614 non-null    object
 3   billing_address      614 non-null    object
 4   billing_city         614 non-null    object
 5   billing_state        310 non-null    object
 6   billing_country      614 non-null    object
 7   billing_postal_code  559 non-null    object
 8   total                614 non-null    float64
dtypes: float64(1), int64(2), object(6)
memory usage: 43.3+ KB

In [42]:
invoice['billing_address'] = invoice['billing_address'].str.replace(',', '', regex=False)
invoice

,invoice_id,customer_id,invoice_date,billing_address,billing_city,billing_state,billing_country,billing_postal_code,total
0,1,18,2017-01-03 00:00:00,627 Broadway,New York,NY,USA,10012-2612,15.84
1,2,30,2017-01-03 00:00:00,230 Elgin Street,Ottawa,ON,Canada,K2P 1L7,9.90
2,3,40,2017-01-05 00:00:00,8 Rue Hanovre,Paris,NaN,France,75002,1.98
3,4,18,2017-01-06 00:00:00,627 Broadway,New York,NY,USA,10012-2612,7.92
4,5,27,2017-01-07 00:00:00,1033 N Park Ave,Tucson,AZ,USA,85719,16.83
...,...,...,...,...,...,...,...,...,...
609,610,55,2020-12-21 00:00:00,421 Bourke Street,Sidney,NSW,Australia,2010,6.93
610,611,52,2020-12-27 00:00:00,202 Hoxton Street,London,NaN,United Kingdom,N1 5LH,1.98
611,612,33,2020-12-27 00:00:00,5112 48 Street,Yellowknife,NT,Canada,X1A 1N6,11.88
612,613,20,2020-12-29 00:00:00,541 Del Medio Avenue,Mountain View,CA,USA,94040-111,8.91
613,614,53,2020-12-30 00:00:00,113 Lupus St,London,NaN,United Kingdom,SW1V 3EN,12.87

In [44]:
invoice.to_csv('invoice.csv', index = False)

In [33]:
invoice_line.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4757 entries, 0 to 4756
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   invoice_line_id  4757 non-null   int64
 1   invoice_id       4757 non-null   int64
 2   track_id         4757 non-null   int64
 3   unit_price       4757 non-null   float64
 4   quantity         4757 non-null   int64
dtypes: float64(1), int64(4)
memory usage: 185.9 KB

In [34]:
invoice_line.columns

Index(['invoice_line_id', 'invoice_id', 'track_id', 'unit_price', 'quantity'], dtype='object')

In [35]:
playlist_track = pd.read_csv('playlist_track.csv')

In [36]:
playlist_track.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8715 entries, 0 to 8714
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   playlist_id  8715 non-null   int64
 1   track_id     8715 non-null   int64
dtypes: int64(2)
memory usage: 136.3 KB

In [37]:
playlist_track.columns

Index(['playlist_id', 'track_id'], dtype='object')

In [38]:
cols = {'genres':list(genres.columns), 
        'artist':list(artist.columns), 
        'media_type':list(media_type.columns),
        'playlist':list(playlist.columns), 
        'customer':list(customer.columns),
        'album':list(album.columns),
        'playlist_track':list(playlist.columns), 
        'invoice':list(invoice.columns), 
        'invoice_line':list(invoice_line.columns)}

In [39]:
cols

{'genres': ['genre_id', 'name'],
 'artist': ['artist_id', 'name'],
 'media_type': ['media_type_id', 'name'],
 'playlist': ['playlist_id', 'name'],
 'customer': ['customer_id',
  'first_name',
  'last_name',
  'company',
  'address',
  'city',
  'state',
  'country',
  'postal_code',
  'phone',
  'fax',
  'email',
  'support_rep_id'],
 'album': ['album_id', 'title', 'artist_id'],
 'playlist_track': ['playlist_id', 'name'],
 'invoice': ['invoice_id',
  'customer_id',
  'invoice_date',
  'billing_address',
  'billing_city',
  'billing_state',
  'billing_country',
  'billing_postal_code',
  'total'],
 'invoice_line': ['invoice_line_id',
  'invoice_id',
  'track_id',
  'unit_price',
  'quantity']}

'genres': ['genre_id', 'name'], \
 'artist': ['artist_id', 'name'], \
 'media_type': ['media_type_id', 'name'], \
 'playlist': ['playlist_id', 'name'], \
 'customer': ['customer_id',  'first_name',  'last_name',  'company',  'address',  'city',  'state',  'country',  'postal_code',  'phone',  'fax',  'email',  'support_rep_id'], \
 'album': ['album_id', 'title', 'artist_id'], \
 'playlist_track': ['playlist_id', 'name'], \
 'invoice': ['invoice_id',  'customer_id',  'invoice_date',  'billing_address',  'billing_city',  'billing_state',  'billing_country',  'billing_postal_code',  'total'], \
 'invoice_line': ['invoice_line_id',  'invoice_id',  'track_id',  'unit_price',  'quantity']